In [53]:
import pandas as pd
import numpy as np

df = pd.read_csv('transaksi_elektronikprima.csv')
df.head()

,id_transaksi,tanggal,cabang,kategori_produk,nama_produk,harga_satuan,jumlah_terjual,total_penjualan,metode_pembayaran,jenis_kelamin_pelanggan,usia_pelanggan,rating_kepuasan,status_promo,biaya_iklan_harian
0,TRX01409,2026-01-01,Surabaya,Laptop,Laptop A14,14493000,1,14493000,E-Wallet,L,57.0,NaN,Reguler,584000
1,TRX00846,2026-01-01,Bandung,Smartphone,Smartphone MaxEdge,7967000,5,39835000,Kredit,L,21.0,NaN,Reguler,1652000
2,TRX01550,2026-01-01,Jakarta,Aksesoris,Mouse Wireless,126000,4,504000,Tunai,P,33.0,5.0,Reguler,1092000
3,TRX01622,2026-01-01,Jakarta,Laptop,Laptop X1,13021000,3,39063000,Kredit,P,39.0,1.0,Reguler,727000
4,TRX01996,2026-01-01,Malang,Smartphone,Smartphone NovaLite,5472000,2,10944000,Kredit,P,41.0,4.0,Reguler,1630000

In [30]:
df.shape

(2200, 14)

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_transaksi             2200 non-null   str
 1   tanggal                  2200 non-null   str
 2   cabang                   2200 non-null   str
 3   kategori_produk          2200 non-null   str
 4   nama_produk              2200 non-null   str
 5   harga_satuan             2200 non-null   int64
 6   jumlah_terjual           2200 non-null   int64
 7   total_penjualan          2200 non-null   int64
 8   metode_pembayaran        2200 non-null   str
 9   jenis_kelamin_pelanggan  2200 non-null   str
 10  usia_pelanggan           2068 non-null   float64
 11  rating_kepuasan          2024 non-null   float64
 12  status_promo             2200 non-null   str
 13  biaya_iklan_harian       2200 non-null   int64
dtypes: float64(2), int64(4), str(8)
memory usage: 240.8 KB

In [32]:
df.describe()

,harga_satuan,jumlah_terjual,total_penjualan,usia_pelanggan,rating_kepuasan,biaya_iklan_harian
count,2.200000e+03,2200.000000,2.200000e+03,2068.000000,2024.000000,2.200000e+03
mean,4.871675e+06,3.075455,1.487367e+07,33.413926,3.986166,1.678751e+06
std,4.017403e+06,1.438361,1.508898e+07,8.729601,0.993208,8.858103e+05
min,5.100000e+04,1.000000,5.900000e+04,18.000000,1.000000,2.020000e+05
25%,1.107250e+06,2.000000,2.372500e+06,27.000000,4.000000,9.470000e+05
50%,4.506000e+06,3.000000,1.080100e+07,33.000000,4.000000,1.659500e+06
75%,7.245500e+06,4.000000,2.249400e+07,39.000000,5.000000,2.363250e+06
max,1.498800e+07,7.000000,8.965800e+07,64.000000,5.000000,4.792000e+06

In [34]:
df['cabang'].nunique()

4

In [35]:
df['cabang'].unique()

<StringArray>
['Surabaya', 'Bandung', 'Jakarta', 'Malang']
Length: 4, dtype: str

In [36]:
df['kategori_produk'].nunique()

4

In [37]:
df['kategori_produk'].unique()

<StringArray>
['Laptop', 'Smartphone', 'Aksesoris', 'Elektronik Rumah Tangga']
Length: 4, dtype: str

In [38]:
df[df['cabang'] == 'Bandung']

,id_transaksi,tanggal,cabang,kategori_produk,nama_produk,harga_satuan,jumlah_terjual,total_penjualan,metode_pembayaran,jenis_kelamin_pelanggan,usia_pelanggan,rating_kepuasan,status_promo,biaya_iklan_harian
1,TRX00846,2026-01-01,Bandung,Smartphone,Smartphone MaxEdge,7967000,5,39835000,Kredit,L,21.0,NaN,Reguler,1652000
7,TRX00773,2026-01-01,Bandung,Smartphone,Smartphone Air,1974000,5,9870000,E-Wallet,P,26.0,NaN,Reguler,1652000
10,TRX01949,2026-01-01,Bandung,Laptop,Laptop ProBook,9489000,3,28467000,E-Wallet,P,34.0,NaN,Reguler,658000
11,TRX01237,2026-01-01,Bandung,Aksesoris,Mouse Wireless,329000,2,658000,Debit,P,41.0,4.0,Reguler,824000
18,TRX01175,2026-01-02,Bandung,Smartphone,Smartphone Z5,2690000,5,13450000,Debit,L,46.0,5.0,Reguler,228000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2181,TRX00347,2026-06-29,Bandung,Smartphone,Smartphone Z5,5626000,2,11252000,E-Wallet,L,46.0,4.0,Reguler,2938000
2186,TRX00820,2026-06-30,Bandung,Smartphone,Smartphone MaxEdge,2852000,3,8556000,E-Wallet,P,31.0,2.0,Reguler,344000
2189,TRX00810,2026-06-30,Bandung,Smartphone,Smartphone Air,7610000,2,15220000,Tunai,L,25.0,3.0,Reguler,1865000
2197,TRX01056,2026-06-30,Bandung,Aksesoris,Earphone Bluetooth,376000,3,1128000,E-Wallet,L,40.0,4.0,Reguler,1857000
2199,TRX01336,2026-06-30,Bandung,Laptop,Laptop ProBook,9496000,1,9496000,E-Wallet,P,47.0,5.0,Reguler,242000

In [39]:
df[df['cabang'] == 'Bandung'].shape

(336, 14)

In [40]:
df[df['cabang'] == 'Bandung'].describe()

,harga_satuan,jumlah_terjual,total_penjualan,usia_pelanggan,rating_kepuasan,biaya_iklan_harian
count,3.360000e+02,336.000000,3.360000e+02,309.000000,303.000000,3.360000e+02
mean,4.588039e+06,3.071429,1.397188e+07,33.025890,3.986799,1.635196e+06
std,3.918643e+06,1.345291,1.407037e+07,8.509695,1.009798,9.177684e+05
min,5.200000e+04,1.000000,1.010000e+05,18.000000,1.000000,2.020000e+05
25%,4.547500e+05,2.000000,1.790500e+06,27.000000,3.500000,9.025000e+05
50%,4.114000e+06,3.000000,1.058400e+07,33.000000,4.000000,1.635500e+06
75%,6.871000e+06,4.000000,2.107400e+07,40.000000,5.000000,2.279500e+06
max,1.498800e+07,7.000000,6.604000e+07,59.000000,5.000000,4.717000e+06

In [47]:
df[df['kategori_produk'] == 'Smartphone']

,id_transaksi,tanggal,cabang,kategori_produk,nama_produk,harga_satuan,jumlah_terjual,total_penjualan,metode_pembayaran,jenis_kelamin_pelanggan,usia_pelanggan,rating_kepuasan,status_promo,biaya_iklan_harian
1,TRX00846,2026-01-01,Bandung,Smartphone,Smartphone MaxEdge,7967000,5,39835000,Kredit,L,21.0,NaN,Reguler,1652000
4,TRX01996,2026-01-01,Malang,Smartphone,Smartphone NovaLite,5472000,2,10944000,Kredit,P,41.0,4.0,Reguler,1630000
7,TRX00773,2026-01-01,Bandung,Smartphone,Smartphone Air,1974000,5,9870000,E-Wallet,P,26.0,NaN,Reguler,1652000
9,TRX00845,2026-01-01,Jakarta,Smartphone,Smartphone Air,1632000,4,6528000,Debit,P,40.0,5.0,Reguler,1258000
16,TRX01279,2026-01-02,Malang,Smartphone,Smartphone MaxEdge,3298000,3,9894000,E-Wallet,L,31.0,5.0,Reguler,1109000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,TRX00161,2026-06-30,Malang,Smartphone,Smartphone Z5,1730000,5,8650000,Debit,P,23.0,4.0,Reguler,2618000
2189,TRX00810,2026-06-30,Bandung,Smartphone,Smartphone Air,7610000,2,15220000,Tunai,L,25.0,3.0,Reguler,1865000
2191,TRX00511,2026-06-30,Malang,Smartphone,Smartphone NovaLite,2393000,1,2393000,E-Wallet,L,NaN,5.0,Reguler,1871000
2196,TRX01422,2026-06-30,Surabaya,Smartphone,Smartphone Z5,7161000,3,21483000,E-Wallet,L,24.0,4.0,Reguler,2324000
2198,TRX01117,2026-06-30,Malang,Smartphone,Smartphone Z5,7533000,2,15066000,E-Wallet,P,21.0,NaN,Reguler,2207000

In [48]:
df[df['kategori_produk'] == 'Smartphone']['metode_pembayaran'].nunique()

4

In [49]:
df[df['kategori_produk'] == 'Smartphone']['metode_pembayaran'].unique()

<StringArray>
['Kredit', 'E-Wallet', 'Debit', 'Tunai']
Length: 4, dtype: str

In [55]:
df['jumlah_terjual'].head()

0    1
1    5
2    4
3    3
4    2
Name: jumlah_terjual, dtype: int64